# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-07 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430', 'verbose_name_plural': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
    ]
